# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3ce87171c934adfa02fe41bba4b3f9f0b5637ffd46524be5946de8a71daf5b64b7a15528b8142acb7968dd52190ef4bb739063d6c9b3aa2211028c730ad0fc5

test:
  secret_key_base: 5e5580a8c41f80d78cf63bf614946baba2cdd3b3243ed0d89371b1f0d6ded7048ef55b419d798ae29c19e70b9c497e0f92c2fa2077d3dd5d5b374f5ff0d44a1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
